### ISSUE TITLE
    - nexylan/graylog-sdk v0.5.0 requires php-http/client-implementation ^1.0 -> no matching package found.

### ISSUE THREAD

**Issue by sirshurf** [nexylan/graylog-sdk#10]
The php-http/client-implementation is no longer availible, use client-common

**Comment by Soullivaneuh** [comment]
The `https://packagist.org/providers/php-http/client-implementation` **is available**, it's a virtual package: https://packagist.org/providers/php-http/client-implementation

The client installation belong to your choice.
