### ISSUE TITLE
Not compatible with php-http/httplug ^2.0

### ISSUE THREAD

**Issue by sirshurf** [nexylan/graylog-sdk#11]
The problem is, if you install httpplug you are getting version 2.0

**Comment by Soullivaneuh** [comment]
@sirshurf You can still require `php-http/httplug:^1.1` manually.

If you want to contribute to propose an upgrade, feel free! :+1:

**Comment by soullivaneuh** [comment]
The project is HTTPlug v2 compatible since https://github.com/nexylan/graylog-sdk/commit/1eec46176efe16a6c7c6169946cf2f4cd822e875.
